export const FETCHING_CURRENT_CHANNEL_INFOS = "FETCHING_CURRENT_CHANNEL_INFOS";
export const SUCCESS_FETCH_CURRENT_CHANNEL_INFOS = "SUCCESS_FETCH_CURRENT_CHANNEL_INFOS";
export const FAIL_FETCH_CURRENT_CHANNEL_INFOS = "FAIL_FETCH_CURRENT_CHANNEL_INFOS";
export const SUCCESS_FETCH_CURRENT_CHANNEL_MESSAGES = "SUCCESS_FETCH_CURRENT_CHANNEL_MESSAGES";
export const FAIL_FETCH_CURRENT_CHANNEL_MESSAGES = "FAIL_FETCH_CURRENT_CHANNEL_MESSAGES";
export const FETCHING_CURRENT_CHANNEL_MESSAGES = "FETCHING_CURRENT_CHANNEL_MESSAGES";
export const SET_CHANNELS_URLS = "SET_CHANNELS_URLS";
