export const FETCHING_PUBLIC_CHANNEL_INFOS = "FETCHING_PUBLIC_CHANNEL_INFOS";
export const SUCCESS_FETCH_PUBLIC_CHANNEL_INFOS = "SUCCESS_FETCH_PUBLIC_CHANNEL_INFOS";
export const FAIL_FETCH_PUBLIC_CHANNEL_INFOS = "FAIL_FETCH_PUBLIC_CHANNEL_INFOS";
export const SUCCESS_FETCH_PUBLIC_CHANNEL_MESSAGES = "SUCCESS_FETCH_PUBLIC_CHANNEL_MESSAGES";
export const FAIL_FETCH_PUBLIC_CHANNEL_MESSAGES = "FAIL_FETCH_PUBLIC_CHANNEL_MESSAGES";
export const FETCHING_PUBLIC_CHANNEL_MESSAGES = "FETCHING_PUBLIC_CHANNEL_MESSAGES";
