export const CONNECTING_USER = "CONNECTING_USER";
export const SUCCESS_CONNECTED_USER = "SUCCESS_CONNECTED_USER";
export const FAIL_CONNECTED_USER = "FAIL_CONNECTED_USER";
export const LOGOUT_USER = "LOGOUT_USER";
